### ISSUE TITLE
the code

### ISSUE THREAD

**Issue by songzongy** [ykdh/MEC-offloading#1]

**Comment by songzongy** [comment]
May I ask whether this code has a reference paper

**Comment by ykdh** [comment]
这是我本科毕设的第一版代码，算法比较简单，你可以知网搜索一下这个文献，我发不了附件
基于深度强化学习的MEC计算卸载和资源分配研究_程百川
其中强化学习的框架来自https://github.com/p0llx/my_MEC_program
















At 2021-05-10 20:43:54, "songzongy" ***@***.***> wrote:

May I ask whether this code has a reference paper
